import{i as p,a as b}from"./assets/vendor-22aaac4a.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();let c="",l=1,d=0;const u=15;async function m(){const r="https://pixabay.com",t="/api/",s=`?key=42153044-59e7d8487fc2c2f8c6f74878d&q=${c}&image_type=photo&orientation=horizontal&safesearch=true&page=${l}&per_page=${u}`,n=`${r}${t}${s}`;return(await b.get(n)).data}const a={formEl:document.querySelector(".search-form"),galleryEl:document.querySelector(".gallery-box"),btnEl:document.querySelector(".search-btn"),btnLoadMore:document.querySelector(".load-btn")};document.querySelector(".loader-box");a.formEl.addEventListener("submit",L);a.btnLoadMore.addEventListener("click",h);a.formEl.addEventListener("input",r=>{a.formEl.elements.word.value.trim()&&(a.btnEl.disabled=!1,a.btnEl.classList.remove("disabled"))});async function h(){l+=1;const r=await m();f(r.hits),g()}async function L(r){r.preventDefault();const t=document.querySelector(".gallery");t&&t.remove(),c=r.target.elements.word.value.trim(),l=1;try{const s=await m();d=s.totalHits;const n='<div class="gallery"></div>';a.galleryEl.insertAdjacentHTML("afterbegin",n),f(s.hits)}catch(s){p.show({timeout:5e3,position:"topCenter",color:"#d11804",messageColor:"white",titleColor:"#FFFFFF",iconColor:"#FFFFFF",message:s.message})}g()}function E({id:r,largeImageURL:t,webformatURL:s,tags:n,likes:e,views:o,comments:i,downloads:y}){return`<a class="gallery-link" href="${t}">
          <div class="gallery-item" id="${r}">
            <img class="gallery-image" src="${s}" alt="${n}" loading="lazy" data-source="${t}"/>
            <div class="info">
              <p class="info-item"><b>Likes</b>${e}</p>
              <p class="info-item"><b>Views</b>${o}</p>
              <p class="info-item"><b>Comments</b>${i}</p>
              <p class="info-item"><b>Downloads</b>${y}</p>
            </div>
          </div>
        </a>`}function f(r){const t=r.map(E).join("");a.galleryEl.querySelector(".gallery").insertAdjacentHTML("beforeend",t)}function g(){Math.ceil(d/u)<=l?a.btnLoadMore.classList.add("hidden"):a.btnLoadMore.classList.remove("hidden")}
//# sourceMappingURL=commonHelpers.js.map
